// Map touched files onto architecture components, and express the result as a
// guided view the archify renderer already knows how to draw.
//
// Highlighting is derived from tool-call evidence, never regenerated by a model:
// the baseline IR is authored once and only the focus set moves. That is the whole
// point — a redrawn diagram certifies nothing, a diff of edited paths against a
// frozen manifest certifies something.

import { relative, isAbsolute } from 'node:path'

export const VIEW_ID = 'touched'
const MAX_VIEWS = 5 // schema: meta.views maxItems

const normalize = (p) => p.replace(/^\.\//, '').replace(/\/+$/, '')

/** Does `file` sit at, or under, the component source `source`? */
export function pathMatches (file, source) {
  const f = normalize(file)
  const s = normalize(source)
  return f === s || f.startsWith(s + '/')
}

/**
 * Component ids whose declared `sources` cover at least one touched file.
 * Absolute touched paths are made relative to `repoRoot` first.
 */
export function touchedComponents (ir, touched, repoRoot) {
  const files = touched.map((p) => (repoRoot && isAbsolute(p) ? relative(repoRoot, p) : p))
  const ids = []

  for (const component of ir.components ?? []) {
    const sources = component.sources ?? []
    const hit = files.some((f) => sources.some((s) => s.path && pathMatches(f, s.path)))
    if (hit) ids.push(component.id)
  }
  return ids
}

/**
 * Return a copy of `ir` carrying a `touched` guided view focused on `ids`.
 *
 * An empty focus set removes the view rather than emitting one: the schema requires
 * `focus` minItems 1, so "nothing touched yet" has no legal representation as a view.
 */
export function withTouchedView (ir, ids, { label = 'Touched this session', note } = {}) {
  const meta = { ...(ir.meta ?? {}) }
  const others = (meta.views ?? []).filter((v) => v.id !== VIEW_ID)

  if (!ids.length) {
    if (others.length) meta.views = others
    else delete meta.views
    return { ...ir, meta }
  }

  const view = { id: VIEW_ID, label, focus: ids }
  if (note) view.note = note.slice(0, 140) // schema: note maxLength 140

  // Our view leads; drop the oldest authored views if the baseline already used the budget.
  meta.views = [view, ...others].slice(0, MAX_VIEWS)
  return { ...ir, meta }
}

/** Convenience: one call from evidence to patched IR. */
export function applyTouched (ir, touched, { repoRoot, note } = {}) {
  const ids = touchedComponents(ir, touched, repoRoot)
  return { ir: withTouchedView(ir, ids, { note }), ids }
}
